name: drr_radio_tracker
description: "An APRS application for all radios"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  radio:
    git:
      # url: https://neuro-pm.com/git/CSSI/RadioLibraryFlutter.git
      url: https://github.com/amirdahal/radio-lib.git
      ref: 'main'
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  toastification: ^1.0.0
  mbtiles: ^0.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.34
  string_validator: ^1.2.0
  sqfentity_gen: ^2.5.0
  sqfentity: ^2.5.0
  http: ^1.4.0
  crypt: ^4.3.1
  flutter_blue_plus_windows: ^1.26.1
  window_manager: ^0.5.1
  event_bus: ^2.0.1
  geolocator: ^14.0.2
  flutter_blue_plus: ^1.34.5
  flutter_map_geojson: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.4
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  msix: ^3.16.10


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/images/
    - assets/phhi.omm.mbtiles

  fonts:
    - family: SmoochSans
      fonts:
        - asset: assets/fonts/SmoochSans.ttf

    - family: Trispace
      fonts:
        - asset: assets/fonts/Trispace.ttf

flutter_launcher_icons:
  # Main source image (1024x1024 PNG recommended)
  image_path: "assets/icon.png"

  # Android (Legacy + Adaptive Icons)
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"  # White background
  adaptive_icon_foreground: "assets/icon.png"

  # iOS (App Icons)
  ios: true
  remove_alpha_ios: true  # Keep transparency

  # Windows (Must be in Map format)
  windows:
    generate: true  # Explicitly enable Windows
    image_path: "assets/icon.png"
    icon_sizes: 256  # Multiple sizes for .ico file

  # macOS (Must be in Map format)
  macos:
    generate: true  # Explicitly enable macOS
    image_path: "assets/icon.png"
    icon_size: 1024  # Single size for .icns file

  # Linux (Must be in Map format)
  linux:
    generate: true  # Explicitly enable Linux
    image_path: "assets/icon.png"
    icon_size: 256  # Default size

msix_config:
  display_name: "DRR Radio Tracker"
  publisher_display_name: "Sofistica"
  identity_name: "Sofistica.SmartRF"
  msix_version: "1.0.0.0"
  logo_path: "assets/icon.png"
  capabilities: internetClient, location, bluetooth