name: aprs
description: "An APRS application for all radios"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  radio:
    git:
      url: https://neuro-pm.com/git/CSSI/RadioLibraryFlutter.git
      ref: 'main'
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  toastification: ^1.0.0
  mbtiles: ^0.4.2
  path_provider: ^2.1.5
#  latlong2: ^0.9.1
#  flutter_map: ^8.1.1
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.34
  string_validator: ^1.2.0
  sqfentity_gen: ^2.5.0
  sqfentity: ^2.5.0
  http: ^1.4.0
  crypt: ^4.3.1
  flutter_blue_plus_windows: ^1.26.1
  window_manager: ^0.5.1
  event_bus: ^2.0.1
  geolocator: ^14.0.2
  flutter_blue_plus: ^1.34.5
  flutter_map_geojson: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/phhi.omm.mbtiles