import 'package:radio/radio.dart';

RadioSetting defaultRadioSetting = RadioSetting(
  channelA: 27,
  channelB: 29,
  scan: true,
  aghfpCallMode: 0,
  doubleChannel: 1,
  squelchLevel: 3,
  tailElim: false,
  autoRelayEn: false,
  autoPowerOn: true,
  keepAghfpLink: false,
  micGain: 3,
  txHoldTime: 0,
  txTimeLimit: 6,
  localSpeaker: 1,
  btMicGain: 3,
  adaptiveResponse: false,
  disTone: false,
  powerSavingMode: false,
  autoPowerOff: 0,
  autoShareLocCh: 29,
  hmSpeaker: 0,
  positioningSystem: 7,
  timeOffset: 10,
  useFreqRange2: false,
  pttLock: false,
  leadingSyncBitEn: false,
  pairingAtPowerOn: false,
  screenTimeout: 24,
  vfoX: 3,
  imperialUnit: true,
  wxMode: 2,
  noaaCh: 0,
  vfolTxPowerX: 0,
  vfo2TxPowerX: 0,
  disDigitalMute: true,
  signalingEccEn: false,
  chDataLock: true,
  vfo1ModFreqX: 0,
  vfo2ModFreqX: 0,
);

AprsSetting defaultAprsSetting = AprsSetting(
  maxFwdTimes: 0,
  timeToLive: 0,
  pttReleaseSendLocation: false,
  pttReleaseSendIdInfo: false,
  pttReleaseSendBssUserId: false,
  shouldShareLocation: true,
  sendPwrVoltage: false,
  packetFormat: PacketFormat.aprs,
  allowPositionCheck: true,
  aprsSsid: 0,
  locationShareInterval: 1800,
  bssUserId: 0,
  pttReleaseIdInfo: "",
  beaconMessage: "",
  aprsSymbol: "",
  aprsCallsign: "",
);

List<RfChannel> defaultChannels = [
  RfChannel(
    channelId: 27,
    txMod: ModulationType.fm,
    txFreq: 146.7,
    rxMod: ModulationType.fm,
    rxFreq: 146.1,
    txSubAudio: 88.5,
    rxSubAudio: 88.5,
    scan: false,
    txAtMaxPower: false,
    talkAround: false,
    bandwidth: BandwidthType.narrow,
    preDeEmphBypass: true,
    sign: true,
    txAtMedPower: true,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: false,
    nameStr: "AUD",
  ),
  RfChannel(
    channelId: 28,
    txMod: ModulationType.fm,
    txFreq: 146.1,
    rxMod: ModulationType.fm,
    rxFreq: 146.7,
    txSubAudio: 88.5,
    rxSubAudio: 88.5,
    scan: false,
    txAtMaxPower: false,
    talkAround: false,
    bandwidth: BandwidthType.narrow,
    preDeEmphBypass: true,
    sign: true,
    txAtMedPower: true,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: false,
    nameStr: "AUD_RPT",
  ),
  RfChannel(
    channelId: 29,
    txMod: ModulationType.fm,
    txFreq: 144.39,
    rxMod: ModulationType.fm,
    rxFreq: 144.39,
    txSubAudio: null,
    rxSubAudio: null,
    scan: false,
    txAtMaxPower: false,
    talkAround: false,
    bandwidth: BandwidthType.wide,
    preDeEmphBypass: true,
    sign: true,
    txAtMedPower: false,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: true,
    nameStr: "APRS",
  ),
];
