import 'package:radio/radio.dart';

RadioSetting defaultRadioSetting = RadioSetting(
  channelA: 0,
  channelB: 1,
  scan: false,
  aghfpCallMode: 0,
  doubleChannel: 0,
  squelchLevel: 3,
  tailElim: true,
  autoRelayEn: false,
  autoPowerOn: true,
  keepAghfpLink: false,
  micGain: 3,
  txHoldTime: 0,
  txTimeLimit: 6,
  localSpeaker: 0,
  btMicGain: 3,
  adaptiveResponse: false,
  disTone: false,
  powerSavingMode: false,
  autoPowerOff: 0,
  autoShareLocCh: 3,
  hmSpeaker: 0,
  positioningSystem: 15,
  timeOffset: 40,
  useFreqRange2: false,
  pttLock: false,
  leadingSyncBitEn: false,
  pairingAtPowerOn: false,
  screenTimeout: 20,
  vfoX: 1,
  imperialUnit: false,
  wxMode: 0,
  noaaCh: 0,
  vfolTxPowerX: 0,
  vfo2TxPowerX: 0,
  disDigitalMute: true,
  signalingEccEn: false,
  chDataLock: true,
  vfo1ModFreqX: 120,
  vfo2ModFreqX: 0,
);

AprsSetting defaultAprsSetting = AprsSetting(
  maxFwdTimes: 0,
  timeToLive: 0,
  pttReleaseSendLocation: true,
  pttReleaseSendIdInfo: false,
  pttReleaseSendBssUserId: false,
  shouldShareLocation: true,
  sendPwrVoltage: false,
  packetFormat: PacketFormat.aprs,
  allowPositionCheck: true,
  aprsSsid: 1,
  locationShareInterval: 1800,
  bssUserId: 0,
  pttReleaseIdInfo: '',
  beaconMessage: '',
  aprsSymbol: "/\$",
  aprsCallsign: '',
);

List<RfChannel> defaultChannels = [
  RfChannel(
    channelId: 0, // 1
    txMod: ModulationType.fm,
    txFreq: 144.7,
    rxMod: ModulationType.fm,
    rxFreq: 144.1,
    txSubAudio: null,
    rxSubAudio: null,
    scan: false,
    txAtMaxPower: false,
    talkAround: false,
    bandwidth: BandwidthType.wide,
    preDeEmphBypass: false,
    sign: true,
    txAtMedPower: false,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: false,
    nameStr: 'DRR',
  ),
  RfChannel(
    channelId: 1, //2
    txMod: ModulationType.fm,
    txFreq: 144.1,
    rxMod: ModulationType.fm,
    rxFreq: 144.7,
    txSubAudio: null,
    rxSubAudio: null,
    scan: false,
    txAtMaxPower: false,
    talkAround: false,
    bandwidth: BandwidthType.wide,
    preDeEmphBypass: false,
    sign: true,
    txAtMedPower: false,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: false,
    nameStr: 'DRR REP',
  ),
  RfChannel(
    channelId: 2, // 3
    txMod: ModulationType.fm,
    txFreq: 144.39,
    rxMod: ModulationType.fm,
    rxFreq: 144.39,
    txSubAudio: null,
    rxSubAudio: null,
    scan: false,
    txAtMaxPower: true,
    talkAround: false,
    bandwidth: BandwidthType.wide,
    preDeEmphBypass: false,
    sign: true,
    txAtMedPower: false,
    txDisable: false,
    fixedFreq: false,
    fixedBandwidth: false,
    fixedTxPower: false,
    mute: true,
    nameStr: 'APRS',
  ),
];
