# For signing the app, follow these steps
# Rename this file to keystore.properties
# Fill the required values below

# Do not commit keystore.properties to git

keyAlias=
keyPassword=
storePassword=

# Generate a jks file inside the app folder
# Add path to upload-keystore.jks file
storeFile=

# For more info, visit: https://developer.android.com/studio/publish