import 'package:drr_radio_tracker/src/features/help/constants/help.mixin.dart';
import 'package:drr_radio_tracker/src/features/help/widgets/builder.widget.dart';
import 'package:flutter/material.dart';

class DrrSettingHelpScreen extends StatelessWidget with HelpPageMixin {
  const DrrSettingHelpScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      padding: EdgeInsets.all(16),
      children: [
        BuildSection(
          title: "Understanding DRR settings",
          content:
              "This guide will help you understand the DRR integration settings available in the app",
        ),

        const SizedBox(height: 16),

        BuildSection(
          title: "Purpose",
          content:
              "Enabling and configuring the DRR setting will let the app communicate with the DRR center by sending the received position beacons and current radio's position.\n"
              "Below are the available configuration and settings",
        ),
        const Divider(height: 32),

        BuildSection(
          title: "Send incoming position to DRR.center",
          content:
              "When this setting is enabled, the app will send all incoming position beacons to the DRR center for position tracking.\n\n"
          "* Enable this option if you want to configure your radio to work as a gateway.\n"
            "* The positions are automatically uploaded to the DRR center. In case of failure, the position is stored in the local database, which will then be uploaded to the DRR center in the next cycle."
        ),

        const Divider(height: 32),

        BuildSection(title: "Send my position to DRR.center", content: "This setting allows the radio handler to send their radio's position to the DRR center.\n" "Once enabled, a form will appear will the following fields:"),
        BuildSteps(steps: [
          "Registered UUID: Enter UUID generated by DRR.center in this input field.",
          "Comment: Enter a custom message to be sent. This is meant for hinting the DRR center about a situation which can be updated as needed.",
          "Location share interval (minutes): From the list of available options, set the interval at which your position should be sent to the DRR center"
        ]),
        Text("* Note: Always recheck your UUID after filling the form.\n" "* Save the setting"),
      ],
    );
  }

  @override
  String get label => "DRR settings guide";
}
